import http from 'node:http';
const ORIGIN='https://cobephim.cfd', UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 Version/18.5 Mobile/15E148 Safari/604.1';
const state={status:'running',started:new Date().toISOString(),pages:0,movies:0,queue:[],seen:[],catalog:[],errors:[]}; const seen=new Set(), map=new Map();
const abs=u=>{try{return new URL(String(u||'').replace(/\\\//g,'/'),ORIGIN).href}catch{return ''}};
const movie=u=>{try{const x=new URL(u);return x.origin===ORIGIN&&/^\/phim\/[^/?#]+\/?$/.test(x.pathname)?x.origin+x.pathname.replace(/\/$/,''):''}catch{return ''}};
const ep=u=>{try{const x=new URL(u);return x.origin===ORIGIN&&/^\/phim\/[^/?#]+\/tap-[^/?#]+/.test(x.pathname)?x.origin+x.pathname:''}catch{return ''}};
const links=h=>[...h.matchAll(/(?:href|src)=["']([^"'#]+)["']/gi)].map(x=>abs(x[1])).filter(Boolean);
async function get(u){const r=await fetch(u,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw Error(r.status+' '+u);return r.text()}
async function worker(){const q=[ORIGIN+'/']; while(q.length){const u=q.shift();if(seen.has(u))continue;seen.add(u);let h;try{h=await get(u)}catch(e){state.errors.push(String(e));continue}state.pages++;const ls=links(h);for(const x of ls){const m=movie(x);if(m&&!map.has(m))map.set(m,{url:m,slug:new URL(m).pathname.split('/').pop(),title:'',poster:'',description:'',year:null,episodes:[]});if(m&&!seen.has(m)&&!q.includes(m))q.push(m)}const m=movie(u);if(m){const row=map.get(m);row.title=((h.match(/<title[^>]*>([^<]+)/i)||[])[1]||'').replace(/\s*[-|].*$/,'').trim();row.description=((h.match(/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']+)/i)||[])[1]||'');row.poster=abs((h.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i)||[])[1]||'');row.year=Number((h.match(/(?:19|20)\d{2}/)||[])[0])||null;row.episodes=[...new Set(ls.map(ep).filter(Boolean))].map(url=>({url,id:new URL(url).pathname.split('/').pop(),resolver:'pending'}));}state.movies=map.size;state.queue=q.slice(0,100);state.catalog=[...map.values()];if(state.pages%10===0)console.log('SCAN',state.pages,state.movies,q.length)}state.status='done';state.finished=new Date().toISOString()}worker().catch(e=>{state.status='error';state.errors.push(String(e))});
http.createServer((req,res)=>{res.setHeader('content-type','application/json; charset=utf-8'); if(req.url==='/health')return res.end(JSON.stringify({status:state.status,pages:state.pages,movies:state.movies,errors:state.errors.length}));res.end(JSON.stringify(state,null,2))}).listen(process.env.PORT||10000,'0.0.0.0');